/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as MyRoomsRouteImport } from './routes/my-rooms'
import { Route as RecordingsRouteImport } from './routes/recordings'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TeamRouteImport } from './routes/team'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms.$roomId'
import { Route as RoomsRoomIdIndexRouteImport } from './routes/rooms.$roomId.index'
import { Route as RoomsRoomIdSummaryRouteImport } from './routes/rooms.$roomId.summary'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRoomsRoute = MyRoomsRouteImport.update({
  id: '/my-rooms',
  path: '/my-rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsRoute = RecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdIndexRoute = RoomsRoomIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoomsRoomIdRoute,
} as any)
const RoomsRoomIdSummaryRoute = RoomsRoomIdSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => RoomsRoomIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/memory': typeof MemoryRoute
  '/my-rooms': typeof MyRoomsRoute
  '/recordings': typeof RecordingsRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/rooms/$roomId': typeof RoomsRoomIdRouteWithChildren
  '/rooms/$roomId/summary': typeof RoomsRoomIdSummaryRoute
  '/rooms/$roomId/': typeof RoomsRoomIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/memory': typeof MemoryRoute
  '/my-rooms': typeof MyRoomsRoute
  '/recordings': typeof RecordingsRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/rooms/$roomId/summary': typeof RoomsRoomIdSummaryRoute
  '/rooms/$roomId': typeof RoomsRoomIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/memory': typeof MemoryRoute
  '/my-rooms': typeof MyRoomsRoute
  '/recordings': typeof RecordingsRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/rooms/$roomId': typeof RoomsRoomIdRouteWithChildren
  '/rooms/$roomId/summary': typeof RoomsRoomIdSummaryRoute
  '/rooms/$roomId/': typeof RoomsRoomIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/memory'
    | '/my-rooms'
    | '/recordings'
    | '/settings'
    | '/team'
    | '/rooms/$roomId'
    | '/rooms/$roomId/summary'
    | '/rooms/$roomId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/memory'
    | '/my-rooms'
    | '/recordings'
    | '/settings'
    | '/team'
    | '/rooms/$roomId/summary'
    | '/rooms/$roomId'
  id:
    | '__root__'
    | '/'
    | '/memory'
    | '/my-rooms'
    | '/recordings'
    | '/settings'
    | '/team'
    | '/rooms/$roomId'
    | '/rooms/$roomId/summary'
    | '/rooms/$roomId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MemoryRoute: typeof MemoryRoute
  MyRoomsRoute: typeof MyRoomsRoute
  RecordingsRoute: typeof RecordingsRoute
  SettingsRoute: typeof SettingsRoute
  TeamRoute: typeof TeamRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-rooms': {
      id: '/my-rooms'
      path: '/my-rooms'
      fullPath: '/my-rooms'
      preLoaderRoute: typeof MyRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings': {
      id: '/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof RecordingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId/': {
      id: '/rooms/$roomId/'
      path: '/'
      fullPath: '/rooms/$roomId/'
      preLoaderRoute: typeof RoomsRoomIdIndexRouteImport
      parentRoute: typeof RoomsRoomIdRoute
    }
    '/rooms/$roomId/summary': {
      id: '/rooms/$roomId/summary'
      path: '/summary'
      fullPath: '/rooms/$roomId/summary'
      preLoaderRoute: typeof RoomsRoomIdSummaryRouteImport
      parentRoute: typeof RoomsRoomIdRoute
    }
  }
}

interface RoomsRoomIdRouteChildren {
  RoomsRoomIdSummaryRoute: typeof RoomsRoomIdSummaryRoute
  RoomsRoomIdIndexRoute: typeof RoomsRoomIdIndexRoute
}

const RoomsRoomIdRouteChildren: RoomsRoomIdRouteChildren = {
  RoomsRoomIdSummaryRoute: RoomsRoomIdSummaryRoute,
  RoomsRoomIdIndexRoute: RoomsRoomIdIndexRoute,
}

const RoomsRoomIdRouteWithChildren = RoomsRoomIdRoute._addFileChildren(
  RoomsRoomIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MemoryRoute: MemoryRoute,
  MyRoomsRoute: MyRoomsRoute,
  RecordingsRoute: RecordingsRoute,
  SettingsRoute: SettingsRoute,
  TeamRoute: TeamRoute,
  RoomsRoomIdRoute: RoomsRoomIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
